import { useState } from 'react'
import Cookies from 'js-cookie'
import { Link, useNavigate } from 'react-router-dom'
import { Input } from './Input'
import { Button } from '../Button'
import client from '../../../utils/auth'
import { ErrorMsg } from '../../Error/ErrorMsg'
import lock from '../../../assets/icon/lock.svg'
import brandLogo from '../../../assets/icon/brandLogo.png'
import visibility from '../../../assets/icon/visibility.svg'
import useForm from '../../../hooks/useForm'

